//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMakeXMLToIntegrador.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabclientes
    {
        public int COD_CLIENTE { get; set; }
        public string nombre_legal { get; set; }
        public string nombre_fantasia { get; set; }
        public string DIRECCION { get; set; }
        public string comuna { get; set; }
        public Nullable<int> cod_ciudad { get; set; }
        public string FONOS { get; set; }
        public string FAX { get; set; }
        public string email_nuestro { get; set; }
        public string email_propio { get; set; }
        public string CONTACTO { get; set; }
        public string representante_legal { get; set; }
        public string rut { get; set; }
        public string giro { get; set; }
        public string rentacar { get; set; }
        public string carpeta { get; set; }
        public string horario { get; set; }
        public string foto_grande { get; set; }
        public string foto_chica { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string facilidades { get; set; }
        public Nullable<System.DateTime> fecha_ultima_act { get; set; }
        public string otros { get; set; }
        public string nomcli { get; set; }
        public string passcli { get; set; }
        public Nullable<int> sucursal { get; set; }
        public string visible { get; set; }
        public Nullable<int> contclie { get; set; }
        public Nullable<System.DateTime> publishedDate { get; set; }
    }
}
