//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMakeXMLToIntegrador.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos
    {
        public string tveh { get; set; }
        public string nveh { get; set; }
        public string nvehplural { get; set; }
    }
}
