//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLoadDataCurifor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabautos
    {
        public int COD_AUTO { get; set; }
        public string fecha_toma_foto { get; set; }
        public string fotografo { get; set; }
        public string digitador { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<int> COD_CLIENTE { get; set; }
        public string nuevo { get; set; }
        public string Tipoveh { get; set; }
        public string Carroceria { get; set; }
        public Nullable<int> COD_MARCA { get; set; }
        public string MODELO { get; set; }
        public string Version { get; set; }
        public Nullable<int> ANO { get; set; }
        public string valor_ref { get; set; }
        public Nullable<int> PESOS { get; set; }
        public Nullable<int> Pesosdos { get; set; }
        public string Potencia { get; set; }
        public string color { get; set; }
        public Nullable<int> km { get; set; }
        public string milla { get; set; }
        public string motor { get; set; }
        public Nullable<int> combustible { get; set; }
        public Nullable<int> Cilindrada { get; set; }
        public string foto_chica { get; set; }
        public string foto_grande { get; set; }
        public string tipo_cambio { get; set; }
        public string aire_acondicionado { get; set; }
        public string tipo_direccion { get; set; }
        public string radio { get; set; }
        public string alzavidrios_electricos { get; set; }
        public string espejos_electricos { get; set; }
        public string frenos_ABS { get; set; }
        public string airbag { get; set; }
        public string unico_dueno { get; set; }
        public string cierre_centralizado { get; set; }
        public string catalitico { get; set; }
        public string fwd { get; set; }
        public string Llantas { get; set; }
        public string Puertas { get; set; }
        public string Alarma { get; set; }
        public string Techo { get; set; }
        public string otros { get; set; }
        public string pass { get; set; }
        public string nom { get; set; }
        public string emailpart { get; set; }
        public string ciudadpart { get; set; }
        public string Convenio { get; set; }
        public string destacado { get; set; }
        public string patente { get; set; }
        public Nullable<int> contauto { get; set; }
        public string foto2 { get; set; }
        public string foto3 { get; set; }
        public string foto4 { get; set; }
        public string foto5 { get; set; }
        public string foto6 { get; set; }
        public string foto7 { get; set; }
        public string foto8 { get; set; }
        public Nullable<int> vendido { get; set; }
        public Nullable<int> falso { get; set; }
        public string reemplazo { get; set; }
        public string financiamiento { get; set; }
        public string seguro { get; set; }
        public string transferencia { get; set; }
        public string horario { get; set; }
        public string nomauto { get; set; }
        public string fonauto { get; set; }
        public Nullable<int> cod_auto_ant { get; set; }
        public Nullable<int> cod_modelo { get; set; }
        public Nullable<int> cod_version { get; set; }
        public Nullable<System.DateTime> publishedDate { get; set; }
        public Nullable<System.DateTime> fechaRepublicado { get; set; }
        public string consignacion { get; set; }
    }
}
