//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLoadDataCurifor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fotosNuevoServer
    {
        public int id_foto { get; set; }
        public int cod_auto { get; set; }
        public string foto { get; set; }
        public int orden { get; set; }
    }
}
