//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class baseprod2Entities : DbContext
    {
        public baseprod2Entities()
            : base("name=baseprod2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SPR_Obtiene_datos_vehiculo_publicar_DM_Result> SPR_Obtiene_datos_vehiculo_publicar_DM(Nullable<int> codauto, ObjectParameter respuesta, ObjectParameter error)
        {
            var codautoParameter = codauto.HasValue ?
                new ObjectParameter("codauto", codauto) :
                new ObjectParameter("codauto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Obtiene_datos_vehiculo_publicar_DM_Result>("SPR_Obtiene_datos_vehiculo_publicar_DM", codautoParameter, respuesta, error);
        }
    
        public virtual int SPR_Actualiza_Estados_publicacion_DM(Nullable<int> codauto, Nullable<int> coddm, Nullable<int> accion, string estado, ObjectParameter respuesta, ObjectParameter error, ObjectParameter codigodemotores)
        {
            var codautoParameter = codauto.HasValue ?
                new ObjectParameter("codauto", codauto) :
                new ObjectParameter("codauto", typeof(int));
    
            var coddmParameter = coddm.HasValue ?
                new ObjectParameter("coddm", coddm) :
                new ObjectParameter("coddm", typeof(int));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPR_Actualiza_Estados_publicacion_DM", codautoParameter, coddmParameter, accionParameter, estadoParameter, respuesta, error, codigodemotores);
        }
    
        public virtual int SPR_Obtiene_CodUsuarioDM_publicar_DM(Nullable<int> codclienteCA, ObjectParameter codIduDM, ObjectParameter error)
        {
            var codclienteCAParameter = codclienteCA.HasValue ?
                new ObjectParameter("codclienteCA", codclienteCA) :
                new ObjectParameter("codclienteCA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPR_Obtiene_CodUsuarioDM_publicar_DM", codclienteCAParameter, codIduDM, error);
        }
    }
}
