//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class baseprod2Entities : DbContext
    {
        public baseprod2Entities()
            : base("name=baseprod2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SPR_Obtiene_datos_vehiculo_publicar_DM_Result> SPR_Obtiene_datos_vehiculo_publicar_DM(Nullable<int> codauto, ObjectParameter respuesta, ObjectParameter error)
        {
            var codautoParameter = codauto.HasValue ?
                new ObjectParameter("codauto", codauto) :
                new ObjectParameter("codauto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Obtiene_datos_vehiculo_publicar_DM_Result>("SPR_Obtiene_datos_vehiculo_publicar_DM", codautoParameter, respuesta, error);
        }
    }
}
